# Ubuntu 14.04 LTS
# Oracle Java 1.8.0_11 64 bit
# Maven 3.3.9
# Jenkins 1.643
# Nano 2.2.6-1ubuntu1

FROM ccr.ccs.tencentyun.com/qcloud/ubuntu:16.04

MAINTAINER Chris Gruel (christopher_a_gruel@homedepot.com)

