resources:
- name: excel-generator
  type: git
  source:
    uri: https://github.com/gezhiwei8899/testExcel.git
    branch: master
    private_key: {{git-private-key}}
    git_config:
    - name: http.sslVerify
      value: false
    username: {{git-user}}
    password: {{git_pwd}}
- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-concourse-go-image}}

jobs:
- name: build
  plan:
  - get: excel-generator
  - task: artifacory
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ccr.ccs.tencentyun.com/gezhiwei8899/ci, tag: 1.0.0}
      inputs:
        - name: excel-generator
      run:
        dir: excel-generator
        path: ci/build.sh
      outputs:
        - name: excel-generator-jar
  - put: docker-image
    params:
      build: excel-generator/ci






